In [ ]:
#Problem-1: Array Creation:
#1
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)

[[5.06389995e-310 0.00000000e+000]
 [1.58101007e-322 2.37151510e-322]]


In [ ]:
#2
import numpy as np
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3
import numpy as np
filled_array = np.full((3,3), 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4
import numpy as np
given_array = np.array([[1,2],[3,4]])
zeros_array = np.zeros_like(given_array)
print(zeros_array)

[[0 0]
 [0 0]]


In [ ]:
#5
import numpy as np
given_array = np.array([[1,2],[3,4]])
ones_array = np.ones_like(given_array)
print(ones_array)

[[1 1]
 [1 1]]


In [ ]:
#6
import numpy as np
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


In [ ]:
#Problem-2: Array Manipulation: Numerical Ranges and Array indexing:
#1
import numpy as np
range_array = np.arange(10,49)
print(range_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#2
import numpy as np
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3
import numpy as np
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
import numpy as np
random_array = np.random.random(30)
mean_value = np.mean(random_array)
print(mean_value)

0.5566241328486747


In [ ]:
#5
import numpy as np
random_array = np.random.random((10,10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random 10x10 array:")
print(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random 10x10 array:
[[0.43165686 0.87171487 0.86751506 0.47274812 0.97151127 0.99047705
  0.08891678 0.95240059 0.43631435 0.64683237]
 [0.50406209 0.94230935 0.01444371 0.20385166 0.4403593  0.57365391
  0.99709481 0.32311539 0.50885234 0.76641636]
 [0.52715944 0.12408841 0.36658965 0.53313868 0.41491559 0.40648776
  0.02480181 0.4919007  0.36518313 0.93757635]
 [0.90082298 0.56487307 0.21833273 0.68858237 0.8734865  0.14196093
  0.16520289 0.13863588 0.96692873 0.45201356]
 [0.47402595 0.83623261 0.05912583 0.63819976 0.63810681 0.24836009
  0.67489967 0.85283566 0.13942669 0.13852271]
 [0.11113893 0.49898555 0.16012502 0.19000394 0.46994141 0.609769
  0.30980777 0.16090629 0.81652985 0.32492526]
 [0.0329979  0.82842448 0.70138032 0.85646275 0.52358985 0.02556073
  0.59169096 0.68625708 0.8773326  0.18382474]
 [0.68318751 0.58190813 0.81178786 0.54178424 0.01952613 0.81838832
  0.38538121 0.56301924 0.64899483 0.73069856]
 [0.0881235  0.67218698 0.4621455  0.88970462 0.68312255 0.462

In [ ]:
#6
import numpy as np
zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7
import numpy as np
arr = [1,2,0,0,4,0]
reversed_array = arr[::-1]
print(reversed_array)

[0, 4, 0, 0, 2, 1]


In [ ]:
#8
import numpy as np
n = 5
array = np.zeros((n, n), dtype=int)
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#9
import numpy as np
matrix = np.zeros((8,8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Problem-3: Array Operations:
#1
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
result1 = x+y
result2 = v+w
print(result1)
print(result2)

[[ 6  8]
 [10 13]]
[20 22]


In [ ]:
#2
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
result1 = x-y
result2 = v-w
print(result1)
print(result2)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [ ]:
#3
import numpy as np
multiplied_array = array * 7
print(multiplied_array)

[[7 7 7 7 7]
 [7 0 0 0 7]
 [7 0 0 0 7]
 [7 0 0 0 7]
 [7 7 7 7 7]]


In [ ]:
#4
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
result1 = x*x
result2 = y*y
result3 = v*v
result4 = w*w
print(result1)
print(result2)
print(result3)
print(result4)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [ ]:
#5
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
dot_product1 = np.dot(x,y)
dot_product2 = np.dot(v,w)
print(dot_product1)
print(dot_product2)

[[19 22]
 [50 58]]
219


In [ ]:
#6
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
conca1 = np.concatenate((x,y), axis=0)
conca2 = np.concatenate((v,w), axis=0)
print(conca1)
print(conca2)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [ ]:
#7
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
conca = np.concatenate((x,v), axis=0)
print(conca)
#The error "ValueError: all the input arrays must have same number of dimensions" occurs because code is trying to concatenate a 2D array (shape: (2, 2)) with a 1D array (shape: (2,)). np.concatenate requires all arrays to have the same number of dimensions.

In [1]:
#Problem-4: Matrix Operations:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A_inv = \n", I)
print("Hence proved: A * A_inv = Identity matrix.\n")

# 2
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("BA = \n", BA)
print("Hence proved: AB and BA are not equal.\n")

# 3
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T = \n", AB_T)
print("B^T * A^T = \n", BT_AT)
print("Hence proved: (AB)^T = B^T * A^T.\n")


A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Hence proved: A * A_inv = Identity matrix.

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Hence proved: AB and BA are not equal.

(AB)^T = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]
Hence proved: (AB)^T = B^T * A^T.



In [2]:
#Linear equation using Inverse Methods
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([[-1],
              [-3],
              [9]])
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("The solution to the system is:")
print(f"x = {X[0][0]}")
print(f"y = {X[1][0]}")
print(f"z = {X[2][0]}")

The solution to the system is:
x = 2.0
y = 1.0
z = -2.0
